### ISSUE TITLE
Bouton "remove" n’apparaît pas 

### ISSUE THREAD

**Issue by sadikuar** [HE-Arc/CSRuby#100]
# Information ⚠️ 💥

Il y a un petit problème qu'il faudrait résoudre, voici les étapes pour le reproduire :

1. S'authentifier
2. Aller dans la recherche et prendre un item
3. Ajouter un "buy order" (ou "sell order")
4. Rafraîchir la page
-> À ce point, le bouton "remove" ne s'affiche pas alors qu'on est authentifier et que c'est notre "buy order"
5. Aller dans la recherche et reprendre le même item
-> Maintenant le bouton apparaît !?

**Comment by nicopraz** [comment]
Fixed during overall refactor
