### ISSUE TITLE
Documentation de l'API

### ISSUE THREAD

**Issue by sadikuar** [HE-Arc/CSRuby#135]
Endpoints

**Comment by sadikuar** [comment]
J'ai réfléchis sur ce que tu as dit pour les routes @NicolasMinnig et maintenant j'ai un doute. Il faudrait vérifier si les actions sur les items doivent avoir une route du type `item/[method]` ou `items/[method]`.

**Comment by sadikuar** [comment]
Si il y aucune information sur ça, alors c'est à nous de le définir.

**Comment by nicopraz** [comment]
De ce que j'ai lu, je dirai qu'il faut plutôt utiliser "items" car on agit sur une collection d'items, avec items/search on récupère tout ceux qui matchent la recherche et avec /items/id on en récuère un parmis la collection d'items 
![image](https://user-images.githubusercontent.com/55592616/78498892-a903b100-774d-11ea-8373-0bab9cb06b78.png)
(si jamais je l'ai pris d'ici https://restfulapi.net/resource-naming/)

**Comment by sadikuar** [comment]
Ok, à changer alors !
